#!/bin/bash
condapythonsetup() {
  #https://becominghuman.ai/how-to-setup-your-windows-10-machine-for-machine-learning-using-ubuntu-bash-shell-b32f01bd31ab
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  bash Miniconda3-latest-Linux-x86_64.sh
  which conda
  which python
  conda install numpy scipy pandas matplotlib jupyter
  conda create -n py2.7 python=2.7 numpy=1.13 scipy
  conda env list
  source activate <env-name>
  conda install scikit-learn
  conda create -n tensorflow
  source activate tensorflow
  conda install numpy scipy pandas matplotlib jupyter scikit-learn

  #https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package
  pip install — ignore-install — upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp36-cp36m-linux_x86_64.whl

  #Jupyter
  source activate <environment>
  jupyter notebook  -—no-browser

  #http://fizzylogic.nl/2018/01/10/my-python-setup-on-windows-10/
}

opencvcpp() {
  #http://www.codebind.com/cpp-tutorial/install-opencv-ubuntu-cpp/
  sudo apt-get update
  sudo apt-get upgrade
  sudo -s
  cd /opt
  git clone https://github.com/Itseez/opencv.git
  git clone https://github.com/Itseez/opencv_contrib.git
  cd opencv
  mkdir release
  cd release
  cmake -D BUILD_TIFF=ON -D WITH_CUDA=OFF -D ENABLE_AVX=OFF -D WITH_OPENGL=OFF -D WITH_OPENCL=OFF -D WITH_IPP=OFF -D WITH_TBB=ON -D BUILD_TBB=ON -D WITH_EIGEN=OFF -D WITH_V4L=OFF -D WITH_VTK=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv_contrib/modules /opt/opencv/
  make -j4
  make install
  ldconfig
  exit
  cd ~
  pkg-config --modversion opencv
  #3.2.x
}
